### ISSUE TITLE
the list swipe not smoothly in segmentedControl style

### ISSUE THREAD

**Issue by Lobooo** [xmartlabs/PagerTabStripView#102]
**Describe the bug**
AS the video shown: ....https://youtube.com/shorts/04RO15ZMCgI?feature=share, it has two parts, when I change default animation to my custom animation, the list swipe smoothly, I don't know the mechanism behind it, the PagerTabStripView style I used is: .pagerTabStripViewStyle(.segmentedControl(backgroundColor: Color(red: 242 / 255, green: 175 / 255, blue: 169 / 255) , padding: EdgeInsets(top: 0, leading: 30, bottom: 0, trailing: 30), placedInToolbar: true))
、、、、
PagerTabStripView -> WrapperPagerTabStripView: 

   .animation(style.pagerAnimation, value: selection)
   .animation(.interactiveSpring(response: 0.15, dampingFraction: 0.86, blendDuration: 0.25), value: translation)

change to

   .animation(.timingCurve(0.4, 0.0, 0.2, 1.0, duration: 0.25), value: selection)
   .animation(.timingCurve(0.4, 0.0, 0.2, 1.0, duration: 0.25), value: translation)

**Versions (please complete the following information):**
 - Device: [e.g. iPhone12]
 - OS: [e.g. iOS16.2]

**Comment by mlorenze** [comment]
With the last updates (in master) is available to set both animations:
```
pagerAnimationOnTap: Animation?
pagerAnimationOnSwipe: Animation?
```

We will review the default animations for both.

Thanks!
