### ISSUE TITLE
[bug] Can not build 3.2.0 with Xcode 14.3

### ISSUE THREAD

**Issue by coffmark** [xmartlabs/PagerTabStripView#128]
**Describe the bug**
version: v3.2.0
path: Sources/NavigationBarStyles/IndicatorBarView.swift

Hello, I'm @coffmark, Thanks for supporting PagerTabStripView.

```
Initializer for conditional binding must have Optional type, not 'CGFloat'
```

Updating to 4.0.0 would resolve this error, but I cannot make this decision as I want to support iOS 15.

Here's the solution. (https://github.com/xmartlabs/PagerTabStripView/compare/3.2.0...coffmark:PagerTabStripView:fix/3.2.0-support-for-xcode14.3?expand=1)

Would you fix and release v3.2.1 ?
Looking forward to your good reply!

**To Reproduce**
1. `git checkout 3.2.0`
2. `open PagerTabStripView.xcworkspace` (open Xcode14.3)
3. Select PagerTabStrip library and build
4. Above error occurs

**Expected behavior**
Build succeeds

**Screenshots**
<img width="2040" alt="Screenshot 2023-04-15 16 29 08" src="https://user-images.githubusercontent.com/52638834/232195779-70537b87-c8a0-4df4-a550-4d7ceb3d0a48.png">

**Versions (please complete the following information):**
- Xcode: Xcode 14.3
 - Lbrary version 3.2.0

**Comment by ylai-msrl** [comment]
@coffmark hello! May I know how you tackle this issue now? I am facing the same issue but seems they not take this issue in consideration...

**Comment by coffmark** [comment]
Hello, @ylai-msrl!
Unfortunately, the solution is to clone repository and fix it.
(see also: https://github.com/xmartlabs/PagerTabStripView/compare/3.2.0...coffmark:PagerTabStripView:fix/3.2.0-support-for-xcode14.3?expand=1)

If you supported iOS 16 or higher, you can resolve the issue by updating to `v4.0.0`.

**Comment by cecipirotto** [comment]
Hi! I push into [v3.2.1](https://github.com/xmartlabs/PagerTabStripView/tree/v3.2.1) the fix to continue using the older version (thanks @coffmark). 

We won't be providing support for older versions of the library. We strongly recommend updating to the latest version to enjoy all the cool new features. Thanks for understanding!

**Comment by coffmark** [comment]
Thanks, @cecipirotto! I really appreciate it!
This issue has been resolved and close!

**Comment by ikolys** [comment]
Hi @cecipirotto, is it possible to add there a tag 3.2.1 also?
