### ISSUE TITLE
PagerTabStripView not working properly on iOS 18

### ISSUE THREAD

**Issue by TheMartas29** [xmartlabs/PagerTabStripView#140]
**Describe the bug**
PagerTabStripView doesnt work as expected on iOS 18 - blank view

**To Reproduce**
Build app for iOS 18 and open screen with PagerTabStripView - it shows with not content or tabs

**Expected behavior**
Work properly

**Screenshots**
screenshots from iPhone simulator with iOS 17.5 and 18
![Simulator Screenshot - iPhone 16 Pro - 2024-09-19 at 14 13 09](https://github.com/user-attachments/assets/2b30c889-fd18-4a93-ba6e-62e11a70e853)
![Simulator Screenshot - iPhone 15 Pro - 2024-09-19 at 14 13 08](https://github.com/user-attachments/assets/b1f8db86-a623-47be-88b5-7084bc03c74c)

**Versions (please complete the following information):**
- Xcode: 16.0
 - Device: iPhone 16 Pro - simulator
 - OS: iOS 18.0
 - Lbrary version: 4.0.0

**Comment by mcfunley** [comment]
Using `HStack` rather than `LazyHStack` for the tabs fixes it, but not sure that's totally acceptable as a fix.

**Comment by jonathansds** [comment]
Also in need of this fix :)

**Comment by mlorenze** [comment]
Thank you @mcfunley! Your PR was merged into master.
