### ISSUE TITLE
Can't build after install via pod

### ISSUE THREAD

**Issue by minhson95th** [xmartlabs/PagerTabStripView#44]
when buid project after install via` pod 'PagerTabStripView', '~> 2.0'` in Xcode 12.4
![image](https://user-images.githubusercontent.com/46039866/132320085-99058a93-f46c-40f5-aaf8-f7122e264a66.png)

**Comment by cecipirotto** [comment]
Hi! Could you update your Xcode to version 12.5?  Let us know if it's still happening

**Comment by minhson95th** [comment]
i can not update Xcode because i use VMware to run macOS, not real device

**Comment by mtnbarreto** [comment]
Hi @minhson95th! The library compatibility requires XCode 12.5+.
