### ISSUE TITLE
Thread 1: Swift runtime failure: Double value cannot be converted to Int because it is either infinite or NaN

### ISSUE THREAD

**Issue by luckycherry** [xmartlabs/PagerTabStripView#45]
NavigationView + TabView  when app in the background
![image](https://user-images.githubusercontent.com/16411680/132327001-c03fe9cd-a0aa-42b9-97d9-67bc8223859a.png)

**Comment by cecipirotto** [comment]
Hello, could you please give us more info to reproduce it?

**Comment by luckycherry** [comment]
NavigationView + TabView 
TabView have two 
index 0  not have PagerTabStripView
index 1  have PagerTabStripView

launch app if do not show  index 1  click home make app in  background  crash will happen

**Comment by badaro48** [comment]
I have the same issue.
Xcode 12.5.1 PagerTabStripView in NavigationView error

struct TestPagerView: View {
    @State var tabSelection : Int = 0
    var body: some View {
        NavigationView {
            VStack {
                PagerTabStripView(selection: $tabSelection) {
                    ForEach(0..<3) { num in
                        ZStack (alignment:.center) {
                            Color.yellow
                            Text("PAGE \(num)")
                        }
                        .pagerTabItem {
                        }
                        .tag(num)
                    }
                }
            }
            .onAppear {
                print("ON APPEAR - VStack")
            }
        }
        .navigationViewStyle(StackNavigationViewStyle())
        .onAppear {
            print("ON APPEAR - NavigationView")
        }
    }
}

**Comment by skywalkerlw** [comment]
![image](https://user-images.githubusercontent.com/2090084/135969428-271ae94a-1757-4f55-9769-f69d4e36d07e.png)

Happens on Xcode 13 iOS 15
