### ISSUE TITLE
Make swipe optional

### ISSUE THREAD

**Issue by antranapp** [xmartlabs/PagerTabStripView#64]
**Is your feature request related to a problem? Please describe.**
I have a slider on a page, and the current horizontal swipe gesture sometimes make it hard to slide the slider

**Describe the solution you'd like**
I want to have an option to disable to swipe gesture to change page. With this, in some situation, I can disable the swipe gesture if I want.

**Describe alternatives you've considered**
We can change slider to a stepper but it is not suitable for all cases

**Additional context**

**Comment by ugomadagu** [comment]
Hi, it looks like this has been removed form the code. Was there something wrong with the feature?
