### ISSUE TITLE
Where is `TitleNavBarItem`? Compilation fails.

### ISSUE THREAD

**Issue by hoon-prestolabs** [xmartlabs/PagerTabStripView#71]
Compilation fails due to lack of symbol `TitleNavBarItem`.

**To Reproduce**
1. Run the first code example in README.

**Expected behavior**
Running.

**Screenshots**
Compile error.

**Versions (please complete the following information):**
- Xcode: 13.1
 - Device: Simulator
 - OS: iOS15
 - Lbrary version 3.1.0

**Comment by cecipirotto** [comment]
Hi! TitleNavBarItem is not part of the library, it's a custom view that you should implement. You have an example in the [Navigation Bar section](https://github.com/xmartlabs/PagerTabStripView#navigation-bar). 
If it's not clear enough I suggest you clone the example project.
