### ISSUE TITLE
Swipe to back animation bug

### ISSUE THREAD

**Issue by alinless** [xmartlabs/PagerTabStripView#72]
**Describe the bug**
When a user makes a swipe gesture instead of a "back" button in the navigation bar, he will see unwanted swipe animations

**To Reproduce**
1. Go to the example app
2. Click on the first scrollable style button
3. Try swipe to back gesture
4. See the bug

**Versions (please complete the following information):**
- Xcode: 13.2
 - Device: iPhone13
 - OS: iOS 15.2
 - Lbrary version 3.1.0

https://user-images.githubusercontent.com/94690815/146549473-5178eb7f-505c-4369-a593-0dc4e1683b7b.mov

**Comment by cecipirotto** [comment]
Hi alinless! 
The issue is fixed on master and it'll be included in the next release. Let me know if it’s still happening
