### ISSUE TITLE
NavigationView causes crash on iOS 14 (not iOS 15.2) when going back to the first tab while using scrollable bar button

### ISSUE THREAD

**Issue by nikitamounier** [xmartlabs/PagerTabStripView#75]
**Describe the bug**
When on a device using iOS 14, SwiftUI crashes unconditionally, when the user goes back to the first tab from any other tab, when a `PagerTabStripView` is wrapped in a `NavigationView` and uses the `.scrollableBarButton()` style. SwiftUI says "CALayer position contains NaN: [nan nan]." 

Also, the blue bar disappears when going to any other tab after initially landing on the first tab when the app first opens.

**To Reproduce**
1. Run on any iOS 14.x (either by downloading an iOS 14 simulator on Xcode or using a device on iOS 14)
2. Create a navigation view
3. Create a `PagerTabStripView` with at least two child elements
4. Use `.scrollableBarButton()` (with any parameters, it's always the same result)
5. When running the program, go on the second / third / n-th tab – this will already cause the blue bar to disappear – and then go back on the first tab (either by pressing the tab button or by swiping)
6. This causes the crash.

**Crash log (not sure if this is useful or not)**
<details>
<summary>Here</summary>
<br>
<img width="1194" alt="Screenshot 2021-12-27 at 00 00 53" src="https://user-images.githubusercontent.com/36044205/147422996-cf087330-54dd-40bc-bd48-a6bc7a02fcd2.png">
<br>
<img width="1190" alt="Screenshot 2021-12-27 at 00 01 19" src="https://user-images.githubusercontent.com/36044205/147423007-dba15201-f9b4-4d0f-8413-1d136243ffbb.png">
<br>
<img width="1198" alt="Screenshot 2021-12-27 at 00 01 45" src="https://user-images.githubusercontent.com/36044205/147423013-3a265184-ed96-44ad-bc5f-ecf2ca268016.png">
</details>

**Expected behavior**
For the bar not to disappear, and for`PagerTabStripView` to go back to the first tab normally.

**Screen recording**

https://user-images.githubusercontent.com/36044205/147422662-a8c80d16-507d-4d06-a984-48876d3c1768.mp4

The bar disappeared when I went to another tab, and then it crashed instantly when I pressed back on "First".

**Example code**
Here's the code I used for the screen recording:
```swift
struct TestView: View {
    var body: some View {
        NavigationView {
            PagerTabStripView {
                Text("First")
                    .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .center)
                    .pagerTabItem {
                        Text("First")
                            .foregroundColor(.blue)
                    }
                    
                Text("Second")
                    .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .center)
                    .pagerTabItem {
                        Text("Second")
                            .foregroundColor(.blue)
                    }
                
                Text("Third")
                    .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .center)
                    .pagerTabItem {
                        Text("Third")
                            .foregroundColor(.blue)
                    }
                
            }
            .pagerTabStripViewStyle(.scrollableBarButton(indicatorBarHeight: 5, tabItemSpacing: 10))
            .navigationTitle("Test")
        }
    }
}


**Versions:**
- Xcode: 13.2.1
 - Device: iPhone X (iOS 14.1) (real device) && iPhone 11 (iOS 14.0.1) (simulator)
 - Library version 3.1.1

**Comment by mtnbarreto** [comment]
We are supporting ios 16+ in the new version. I checked and seems it works properly now.
