### ISSUE TITLE
iOS 14 scrollableBarButton scroll bar still disappears in a tab view

### ISSUE THREAD

**Issue by skywalkerdude** [xmartlabs/PagerTabStripView#77]
Repost of https://github.com/xmartlabs/PagerTabStripView/issues/63 since it looks like it's still happening.

**Describe the bug**
On iOS14 builds, sometimes the scroll bar disappears

**To Reproduce**
1. Replace `ContentView` in the Example app with:
```
import SwiftUI
import PagerTabStripView

struct ContentView: View {
    
    var body: some View {
        NavigationView {
            TabView {
                InstagramView().tabItem {Text("InstagramView").maxWidth()}.hideNavigationBar()
                TwitterView().tabItem {Text("TwitterView").maxWidth()}.hideNavigationBar()
                YoutubeView().tabItem {Text("YoutubeView").maxWidth()}.hideNavigationBar()
                SegmentedView().tabItem {Text("SegmentedView").maxWidth()}.hideNavigationBar()
                BarStyleView().tabItem {Text("BarStyleView").maxWidth()}.hideNavigationBar()
            }
        }
    }
}

extension View {
    
    func hideNavigationBar() -> some View {
        self
            .navigationBarTitle("", displayMode: .inline)
            .navigationBarHidden(true)
    }
    
    func maxWidth(alignment: Alignment = .center) -> some View {
        self.frame(minWidth: .zero, idealWidth: .infinity, maxWidth: .infinity, alignment: alignment)
    }
}
```
2. Run Example App
3. Click on "TwitterView"
4. Click on "Short"
5. Click on "SegmentedView
6. Click on "BarStyleView""
7. Click back to "TwitterView"
8. Click on "Medium width"
9. Observe the bar disappear

**Expected behavior**
Scroll bar should not run away

**Screenshots**
See video in `Additional Context` section

**Versions (please complete the following information):**
- Xcode: 13.2.1
 - Device: iPhone 11 Pro Simulator
 - OS: iOS 14.5
 - Library version: 3.0.0

**Additional context**
Bug is reproducible in this branch: 
https://github.com/skywalkerdude/PagerTabStripView/blob/tabviewbug/Example/Shared/Additional%20Example%20Source%20Code/ContentView.swift

https://user-images.githubusercontent.com/1427524/148024607-f7a38844-48d1-4ee9-9d27-ebecc0717966.mov

**Comment by cecipirotto** [comment]
Hi, sorry for the late response. It seems that it's an Apple issue. We're using the `scrollTo(selection, anchor: .center)` function and it works ok on iOS 15.  We haven't found another simple approach for this issue.
