### ISSUE TITLE
Is there a way to customize the indicator bar length?

### ISSUE THREAD

**Issue by skywalkerdude** [xmartlabs/PagerTabStripView#81]
**Is your feature request related to a problem? Please describe.**
I would like way to customize the indicator bar length in a `scrollableBarButton`

**Describe the solution you'd like**
In addition to `indicatorBarHeight` and `indicatorBarColor`, maybe we can have an `indicatorBarLength` as well

**Describe alternatives you've considered**
I tried to use the custom `PagerStyle`, but wasn't able to figure out how to get both a scrollable bar and indicator height

Something like this is what I'm looking for. Notice that the indicator goes beyond the title for a bit on both sides.
![Simulator Screen Shot - iPhone 11 Pro - 2022-03-28 at 00 03 51](https://user-images.githubusercontent.com/1427524/160343989-953a5bd3-4cb3-4525-9c24-5622d57b7549.png)
![Simulator Screen Shot - iPhone 11 Pro - 2022-03-28 at 00 04 13](https://user-images.githubusercontent.com/1427524/160344038-cfa93cfa-aa5d-4350-937c-e8d355866bdd.png)

**Comment by cecipirotto** [comment]
Hi! You can do that by modifying your navigation bar view. 
For example, using the scrollable style in the example project:
**1) Fixed navigation bar item size:**
You can set your item size by adding the frame modifier
```
    var body: some View {
        VStack {
            Text(title)
                .foregroundColor(theme.textColor)
                .font(.subheadline)
        }
        .background(Color.clear)
        .frame(width: 100)
    }
```
![Simulator Screen Recording - iPhone 12 - 2022-03-28 at 15 05 36](https://user-images.githubusercontent.com/31603856/160460398-0c645967-0727-4e59-b21e-672d601d0f1e.gif)


**2) Adding padding to your navigation bar item**

```
    var body: some View {
        VStack {
            Text(title)
                .foregroundColor(theme.textColor)
                .font(.subheadline)
        }
        .background(Color.clear)
        .padding(.horizontal, 30)
    }
```


![Simulator Screen Recording - iPhone 12 - 2022-03-28 at 15 12 41](https://user-images.githubusercontent.com/31603856/160460593-be5930ba-0122-4b75-9979-22d40da5e577.gif)

I hope this helps you :D

**Comment by skywalkerdude** [comment]
thanks!! :)
