### ISSUE TITLE
How to set padding parameter when PagerStyle is custom

### ISSUE THREAD

**Issue by CodingDGSun** [xmartlabs/PagerTabStripView#85]
internal var padding: EdgeInsets {
        switch self {
        case .segmentedControl(_, let padding, _):
            return padding
        case .scrollableBarButton(_, _, let padding, _, _, _):
            return padding
        default:
            return EdgeInsets(top: 5, leading: 10, bottom: 0, trailing: 10)
        }
    }

source code has no padding setting for custom type, but I want to set padding parameter when PagerStyle is custom, how can I do?

.pagerTabStripViewStyle(.custom(tabItemSpacing: 0, tabItemHeight: 44, placedInToolbar: false, indicator: {
       // I want to set padding parameter when PagerStyle is custom,
        }, background: {
            
        }))

**Comment by mlorenze** [comment]
With the latest updates the style **.custom** it is no longer available.
The current styles are been modified to support customization in other way, more flexible. 
In the readme file you can see how to customize using the current styles.

**Comment by CodingDGSun** [comment]
您发给我的信件已经收到~O(∩_∩)O~

Your message has received，thank you for your mail.You received this email because the recipient set up an auto-response.
