### ISSUE TITLE
Pushing SegmentedController inside UIHostingController with UIKit - segmented controller is not visible

### ISSUE THREAD

**Issue by galblank** [xmartlabs/PagerTabStripView#87]
**Describe the bug**

**To Reproduce**
**Screenshots**
No segmented controller is visible here:
![Simulator Screen Shot - iPhone 12 Pro - 2022-08-29 at 10 58 18](https://user-images.githubusercontent.com/649080/187232521-3546433f-9ccd-458a-96f0-c4bdc7f7ecc5.png)

XCode View of SwiftUI:
![Screen Shot 2022-08-29 at 10 59 16 AM](https://user-images.githubusercontent.com/649080/187232614-8e3a040f-11ec-4b36-95c6-b0a8303741e9.png)

**Versions (please complete the following information):**
- Xcode: 13.14.1
 - Device: Simulator
 - OS: 15.5
 - Lbrary version : latest

**Additional context**
This is the View that uses segmentedControl

`struct DrillsSelectionSegmentedView: View {
    @State var selection = 0
    var title = ""
    @ObservedObject var striveDrills = SelectableDrillsModel()

    var body: some View {
        PagerTabStripView(selection: $selection) {
            SelectDrillsTableView(isLoading: $striveDrills.isLoading, items: striveDrills.drills ?? [Drill]()).pagerTabItem {
                Text("Strive Drills".localized())
            }
            SelectDrillsTableView(isLoading: $striveDrills.isLoading, items: striveDrills.drills ?? [Drill]()).pagerTabItem {
                Text("My Drills".localized())
            }
        }
        .frame(alignment: .center)
        .pagerTabStripViewStyle(.segmentedControl(backgroundColor: Color(systemLightBlueColor),
                                                  padding: EdgeInsets(top: 50, leading: 0, bottom: 0, trailing: 0),
                                                  placedInToolbar: false))
        .navigationTitle(title)
        .background(Color(systemGrayBgColor))
    }
}
`

This is how it's being displayed from other viewController

```
var addDrillsView = DrillsSelectionSegmentedView()
            let drillsVC = UIHostingController(rootView: addDrillsView)
            sSelf.tabBarController?.tabBar.isHidden = true
            sSelf.navigationController?.pushViewController(drillsVC, animated: true)
            SelectableDrillsFactory.shared.drillFocus = drillFocus
```

**Comment by mlorenze** [comment]
> [galblank](/galblank)

Hi! Thanks to use our framework.
We make support only for SwiftUI (supporting for issues, possible improvements, etc).
