### ISSUE TITLE
Is it easily possible to also animate the [scrollableBarButton - indicatorBar ] as oppose to making it snappy?

### ISSUE THREAD

**Issue by waelsaad** [xmartlabs/PagerTabStripView#89]
Hi, thank you for the project.

Is it easily possible to also animate the  **indicatorBar**  for the style scrollableBarButton as the index changes as oppose to making it snappy? iOS 15

I am refering to the blue bar below each tab.

<img width="359" alt="Screen Shot 2022-10-06 at 11 31 26 am" src="https://user-images.githubusercontent.com/4057766/194187767-4ab41aaf-17dc-4248-a958-20f2cef2f32b.png">

Thank you.

**Comment by mlorenze** [comment]
In the last updates (on master) is available for the user to set the indicator view.
Also the indicator views is animated when the selection is changed.
